"""
Regenerates api/catalog_data.py from a product CSV export.

Run this any time the SuperMed Pharmacy product sheet changes:

    python3 build_catalog.py path/to/products.csv

Expected CSV columns (matches the current export from the site):
    product, brand, category, product_type, package_size,
    active_ingredient_or_key_ingredient, price_jmd, price_numeric_jmd,
    shop_page, source_url, data_quality_note

Only the fields the chatbot actually needs are kept, to minimize the
token count of the catalog that gets sent to OpenAI on every request.
"""

import csv
import json
import sys

OUTPUT_PATH = "api/catalog_data.py"


def build_catalog(csv_path: str) -> list[dict]:
    with open(csv_path, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    catalog = []
    for row in rows:
        name = (row.get("product") or "").strip()
        if not name:
            continue

        brand = (row.get("brand") or "").strip()
        if brand.lower() in ("generic / not stated", "not stated", ""):
            brand = ""

        ingredient = (row.get("active_ingredient_or_key_ingredient") or "").strip()
        if ingredient.lower().startswith("not identifiable"):
            ingredient = ""

        catalog.append(
            {
                "name": name,
                "brand": brand,
                "category": (row.get("category") or "").strip(),
                "ingredient": ingredient,
                "price_jmd": (row.get("price_jmd") or "").strip(),
                "url": "https://supermedpharmacy.com/shop/",
            }
        )

    return catalog


def main():
    if len(sys.argv) != 2:
        print("Usage: python3 build_catalog.py path/to/products.csv")
        sys.exit(1)

    catalog = build_catalog(sys.argv[1])

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by build_catalog.py — do not edit by hand.\n")
        f.write("# Regenerate whenever the product sheet changes.\n\n")
        f.write("PRODUCTS = ")
        json.dump(catalog, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print(f"Wrote {len(catalog)} products to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
